version: '3.7'

services:
  pg:
    image: postgres:13.1
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
    volumes:
      - ./pg_setup:/docker-entrypoint-initdb.d
    ports:
      - '54321:5432'